#############################################################################
# Makefile for building: bin/epitraits
# Generated by qmake (3.0) (Qt 5.3.0)
# Project:  epitraits.pro
# Template: app
# Command: /home/jarpon/Qt5/5.3/gcc_64/bin/qmake -spec linux-g++ -o Makefile epitraits.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = /home/jarpon/Qt5/5.3/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: epitraits.pro ../../../Qt5/5.3/gcc_64/mkspecs/linux-g++/qmake.conf ../../../Qt5/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/unix.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/linux.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/qconfig.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/spec_post.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/default_pre.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/exclusive_builds_post.prf \
		../../../Qt5/5.3/gcc_64/mkspecs/features/default_post.prf \
		epitraits.pro
	$(QMAKE) -spec linux-g++ -o Makefile epitraits.pro
../../../Qt5/5.3/gcc_64/mkspecs/features/spec_pre.prf:
../../../Qt5/5.3/gcc_64/mkspecs/common/shell-unix.conf:
../../../Qt5/5.3/gcc_64/mkspecs/common/unix.conf:
../../../Qt5/5.3/gcc_64/mkspecs/common/linux.conf:
../../../Qt5/5.3/gcc_64/mkspecs/common/gcc-base.conf:
../../../Qt5/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../Qt5/5.3/gcc_64/mkspecs/common/g++-base.conf:
../../../Qt5/5.3/gcc_64/mkspecs/common/g++-unix.conf:
../../../Qt5/5.3/gcc_64/mkspecs/qconfig.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt5/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt5/5.3/gcc_64/mkspecs/features/qt_functions.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/qt_config.prf:
../../../Qt5/5.3/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../Qt5/5.3/gcc_64/mkspecs/features/spec_post.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/default_pre.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/resolve_config.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/exclusive_builds_post.prf:
../../../Qt5/5.3/gcc_64/mkspecs/features/default_post.prf:
epitraits.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ -o Makefile epitraits.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
